import Link from "next/link";
import { LegalShell } from "@/components/landing/LegalShell";

function Section({ num, title, children }: { num: string; title: string; children: React.ReactNode }) {
  return (
    <section>
      <div className="flex items-baseline gap-3 mb-3">
        <span className="text-[11px] font-mono text-blue-400 shrink-0">{num}</span>
        <h2 className="text-sm font-bold text-zinc-200 uppercase tracking-wide">{title}</h2>
      </div>
      <div className="pl-8 text-sm text-zinc-400 leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      subtitle="By accessing or using CTI Tracker, you agree to be bound by these terms. Please read them carefully."
      updated="June 2026"
    >
      <Section num="01" title="Permitted Use">
        <p>
          CTI Tracker is provided exclusively for educational purposes, authorized security research, and
          defensive threat intelligence analysis. You must not use the platform, its data, or any
          indicators obtained from it to conduct unauthorized access to systems or networks, facilitate
          malicious activity, or violate any applicable law.
        </p>
        <p>
          You are solely responsible for ensuring your use of the platform complies with all applicable
          laws and regulations in your jurisdiction, including computer access laws, data protection
          regulations, and export control requirements.
        </p>
      </Section>

      <Section num="02" title="No Warranty">
        <p>
          The platform, all IOC indicators, threat intelligence data, and generated reports are provided{" "}
          <strong className="text-zinc-300">"AS IS"</strong> without warranty of any kind. Threat
          intelligence data is sourced from public open-source feeds and may contain errors,
          inaccuracies, outdated entries, or false positives. CTI Tracker makes no guarantee as to the
          accuracy, completeness, currency, or fitness for a particular purpose of any data displayed
          or generated by the platform.
        </p>
      </Section>

      <Section num="03" title="No Professional Security Advice">
        <p>
          Nothing on this platform constitutes professional cybersecurity, legal, compliance, or other
          professional advice. Intelligence reports generated by the platform are automated informational
          outputs and should not be relied upon as the sole basis for any security decision, operational
          action, or policy change. Consult qualified security professionals before acting on platform
          data.
        </p>
      </Section>

      <Section num="04" title="Third-Party Data Attribution">
        <p>IOC data integrated into this platform is sourced from the following third-party providers:</p>
        <ul className="mt-2 space-y-3 list-none">
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">·</span>
            <span>
              <strong className="text-zinc-300">MalwareBazaar, URLhaus, FeodoTracker</strong> — provided
              by abuse.ch under the{" "}
              <a
                href="https://creativecommons.org/publicdomain/zero/1.0/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-zinc-400 hover:text-zinc-200 underline transition-colors"
              >
                CC0 1.0 Universal
              </a>{" "}
              public domain dedication.
            </span>
          </li>
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">·</span>
            <span>
              <strong className="text-zinc-300">MITRE ATT&amp;CK®</strong> — © 2024 The MITRE
              Corporation. Used under the{" "}
              <a
                href="https://github.com/mitre-attack/attack-stix-data/blob/master/LICENSE"
                target="_blank"
                rel="noopener noreferrer"
                className="text-zinc-400 hover:text-zinc-200 underline transition-colors"
              >
                Apache 2.0 License
              </a>
              . "ATT&amp;CK" and "MITRE ATT&amp;CK" are registered trademarks of The MITRE Corporation.
            </span>
          </li>
        </ul>
      </Section>

      <Section num="05" title="No Affiliation">
        <p>
          CTI Tracker is an independent portfolio project. It is not affiliated with, sponsored by, or
          endorsed by CrowdStrike, Inc., The MITRE Corporation, abuse.ch, or any other company or
          organization referenced in or by the platform. Any similarity to commercial products is for
          demonstration purposes only.
        </p>
      </Section>

      <Section num="06" title="Limitation of Liability">
        <p>
          To the fullest extent permitted by applicable law, CTI Tracker and its operators shall not be
          liable for any direct, indirect, incidental, special, or consequential damages arising from
          your use of or reliance on the platform. This includes damages arising from false positives
          in threat data, security incidents, data loss, or decisions made based on generated reports.
        </p>
      </Section>

      <Section num="07" title="Account Termination">
        <p>
          Platform operators reserve the right to suspend or terminate accounts that violate these terms
          or for any operational reason, with or without notice.
        </p>
      </Section>

      <Section num="08" title="Changes">
        <p>
          These terms may be updated at any time. Continued use of the platform following any changes
          constitutes your acceptance of the revised terms.
        </p>
      </Section>

      <div className="pt-4 border-t border-zinc-800">
        <p className="text-xs text-zinc-600">
          See also:{" "}
          <Link href="/legal/privacy" className="text-zinc-500 hover:text-zinc-300 underline transition-colors">
            Privacy Policy
          </Link>{" "}
          ·{" "}
          <Link href="/legal/disclaimer" className="text-zinc-500 hover:text-zinc-300 underline transition-colors">
            Intelligence Disclaimer
          </Link>
        </p>
      </div>
    </LegalShell>
  );
}
