const fs   = require("fs");
const path = require("path");
const { getCampaignSummary } = require("./analyzers/campaign");

const REPORTS_DIR = path.join(__dirname, "..", "reports");
fs.mkdirSync(REPORTS_DIR, { recursive: true });

const TLP_LABELS = {
  "TLP:WHITE": "TLP:WHITE — Unlimited distribution",
  "TLP:GREEN": "TLP:GREEN — Distribution to community",
  "TLP:AMBER": "TLP:AMBER — Limited distribution",
  "TLP:RED":   "TLP:RED   — Personal recipients only",
};

const IOC_TYPE_LABELS = {
  hash_md5:    "MD5 Hashes",
  hash_sha1:   "SHA1 Hashes",
  hash_sha256: "SHA256 Hashes",
  ip:          "IP Addresses",
  domain:      "Domains",
  url:         "URLs",
};

function nowUtc() {
  return new Date().toISOString().replace("T", " ").replace(/\.\d{3}Z$/, " UTC");
}

async function generateTacticalReport(campaignId, tlp = "TLP:WHITE") {
  const summary = await getCampaignSummary(campaignId);
  if (!summary) return [null, "Campaign not found."];

  const { campaign: c } = summary;
  const now   = nowUtc();
  const title = `Tactical Intelligence Report: ${c.name}`;
  const tlpLabel = TLP_LABELS[tlp] ?? tlp;

  const lines = [
    `# ${title}`, "",
    "| Field | Value |",
    "|-------|-------|",
    `| **Classification** | ${tlpLabel} |`,
    `| **Report Date**    | ${now} |`,
    `| **Report Type**    | Tactical |`,
    `| **Campaign**       | ${c.name} |`,
    `| **Threat Actor**   | ${c.threat_actor || "Unknown"} |`,
    `| **Motivation**     | ${(c.motivation || "unknown").charAt(0).toUpperCase() + (c.motivation || "unknown").slice(1)} |`,
    `| **Status**         | ${(c.status || "active").charAt(0).toUpperCase() + (c.status || "active").slice(1)} |`,
    "",
    "## Executive Summary", "",
    `This report provides a tactical assessment of adversary activity associated with the **${c.name}** campaign. ` +
    `Analysts have identified **${summary.total_iocs}** indicators of compromise (IOCs) and **${summary.ttps.length}** MITRE ATT&CK techniques attributed to this campaign.`,
    "",
  ];

  if (c.description) lines.push(c.description, "");

  if (summary.malware_families.length) {
    lines.push("## Associated Malware Families", "");
    for (const fam of summary.malware_families) lines.push(`- **${fam}**`);
    lines.push("");
  }

  if (summary.ttps.length) {
    lines.push("## Adversary TTPs (MITRE ATT&CK)", "",
      "| Technique ID | Technique Name | Tactic | Notes |",
      "|-------------|----------------|--------|-------|");
    for (const ttp of summary.ttps) {
      lines.push(`| ${ttp.technique_id} | ${ttp.technique_name || ""} | ${ttp.tactic || ""} | ${ttp.notes || ""} |`);
    }
    lines.push("");
  }

  lines.push("## Indicators of Compromise (IOCs)", "", `**Total:** ${summary.total_iocs}`, "");
  for (const [iocType, values] of Object.entries(summary.ioc_by_type)) {
    const label = IOC_TYPE_LABELS[iocType] ?? iocType;
    lines.push(`### ${label}`, "", "```", ...values, "```", "");
  }

  lines.push(
    "## Defensive Recommendations", "",
    "1. **Block listed IOCs** at perimeter controls (firewall, proxy, DNS sinkhole).",
    "2. **Retrospective hunt**: search SIEM and EDR telemetry for historical hits.",
    "3. **Validate detection coverage** against each observed ATT&CK technique.",
    "4. **Review ATT&CK mitigations** at attack.mitre.org for each technique ID.",
    "5. **Increase logging** on assets targeted by this adversary's known sectors.",
    "", "---",
    `*Generated by CTI Tracker | ${now} | ${tlpLabel}*`
  );

  return [title, lines.join("\n")];
}

function saveReportFile(title, content) {
  const safe = title.replace(/[^a-zA-Z0-9 \-_]/g, "_").slice(0, 60);
  const outPath = path.join(REPORTS_DIR, `${safe}.md`);
  fs.writeFileSync(outPath, content, "utf8");
  return outPath;
}

module.exports = { generateTacticalReport, saveReportFile };
