"""
Finished Intelligence Report Generator.

Real CTI reports follow the Intelligence Production Cycle:
  Planning → Collection → Processing → Analysis → Dissemination

Two report types are implemented:

  Tactical report   — IOC list + TTP table for defenders/SOC teams.
                      Answers: "What exactly did they use and how do I block it?"

  Flash report      — Single-IOC alert for time-sensitive notifications.
                      Answers: "Is this thing I just found malicious?"

Reports are formatted in Markdown so they can be:
  - Rendered in GitHub / Confluence / any wiki
  - Converted to PDF with pandoc
  - Pasted into a ticketing system

TLP (Traffic Light Protocol) governs how widely a report may be shared:
  WHITE  Unlimited — public
  GREEN  Community sharing — ISACs, trusted partners
  AMBER  Limited — recipient organisations only
  RED    Personal — named recipients only
"""

from datetime import datetime
from analyzers.campaign_tracker import get_campaign_summary

_TLP_LABELS = {
    "TLP:WHITE": "TLP:WHITE — Unlimited distribution",
    "TLP:GREEN": "TLP:GREEN — Distribution to community",
    "TLP:AMBER": "TLP:AMBER — Limited distribution",
    "TLP:RED":   "TLP:RED   — Personal recipients only",
}

_IOC_TYPE_LABELS = {
    "hash_md5":    "MD5 Hashes",
    "hash_sha1":   "SHA1 Hashes",
    "hash_sha256": "SHA256 Hashes",
    "ip":          "IP Addresses",
    "domain":      "Domains",
    "url":         "URLs",
}


def _now() -> str:
    return datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")


def generate_tactical_report(
    campaign_id: int,
    tlp: str = "TLP:WHITE",
) -> tuple[str, str]:
    """
    Generate a tactical intelligence report for a campaign.
    Returns (title, markdown_content).
    """
    summary = get_campaign_summary(campaign_id)
    if not summary:
        return "", "Campaign not found."

    c   = summary["campaign"]
    now = _now()
    title = f"Tactical Intelligence Report: {c['name']}"

    lines = [
        f"# {title}",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Classification** | {_TLP_LABELS.get(tlp, tlp)} |",
        f"| **Report Date**    | {now} |",
        f"| **Report Type**    | Tactical |",
        f"| **Campaign**       | {c['name']} |",
        f"| **Threat Actor**   | {c.get('threat_actor') or 'Unknown'} |",
        f"| **Motivation**     | {c.get('motivation', 'unknown').title()} |",
        f"| **Status**         | {c.get('status', 'active').title()} |",
        "",
        "## Executive Summary",
        "",
        (
            f"This report provides a tactical assessment of adversary activity "
            f"associated with the **{c['name']}** campaign. "
            f"Analysts have identified **{summary['total_iocs']}** indicators of "
            f"compromise (IOCs) and **{len(summary['ttps'])}** MITRE ATT&CK "
            f"techniques attributed to this campaign."
        ),
        "",
    ]

    if c.get("description"):
        lines += [c["description"], ""]

    if summary["malware_families"]:
        lines += ["## Associated Malware Families", ""]
        for fam in summary["malware_families"]:
            lines.append(f"- **{fam}**")
        lines.append("")

    if summary["ttps"]:
        lines += [
            "## Adversary TTPs (MITRE ATT&CK)",
            "",
            "| Technique ID | Technique Name | Tactic | Notes |",
            "|-------------|----------------|--------|-------|",
        ]
        for ttp in summary["ttps"]:
            lines.append(
                f"| {ttp['technique_id']} "
                f"| {ttp.get('technique_name', '')} "
                f"| {ttp.get('tactic', '')} "
                f"| {ttp.get('notes', '')} |"
            )
        lines.append("")

    lines += [
        "## Indicators of Compromise (IOCs)",
        "",
        f"**Total:** {summary['total_iocs']}",
        "",
    ]

    for ioc_type, values in summary["ioc_by_type"].items():
        label = _IOC_TYPE_LABELS.get(ioc_type, ioc_type)
        lines += [f"### {label}", "", "```"]
        lines += values
        lines += ["```", ""]

    lines += [
        "## Defensive Recommendations",
        "",
        "1. **Block listed IOCs** at perimeter controls (firewall, proxy, DNS sinkhole).",
        "2. **Retrospective hunt** — search SIEM and EDR telemetry for historical hits.",
        "3. **Validate detection coverage** against each observed ATT&CK technique.",
        "4. **Review ATT&CK mitigations** at attack.mitre.org for each technique ID.",
        "5. **Increase logging** on assets targeted by this adversary's known sectors.",
        "",
        "---",
        f"*Generated by CTI Tracker | {now} | {_TLP_LABELS.get(tlp, tlp)}*",
    ]

    return title, "\n".join(lines)


def generate_flash_report(ioc_value: str, analysis: dict) -> tuple[str, str]:
    """
    Generate a Flash (single-IOC alert) report.
    Returns (title, markdown_content).
    """
    now   = _now()
    title = f"FLASH: {ioc_value[:50]}"

    lines = [
        f"# FLASH REPORT — Newly Identified IOC",
        "",
        f"**Date:** {now}  ",
        f"**TLP:** TLP:WHITE  ",
        "",
        "## IOC Details",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Indicator**      | `{ioc_value}` |",
        f"| **Type**           | {analysis.get('type', 'Unknown')} |",
        f"| **Malware Family** | {analysis.get('malware_family') or 'Unknown'} |",
        f"| **Threat Type**    | {analysis.get('threat_type') or 'Unknown'} |",
        f"| **First Seen**     | {analysis.get('first_seen') or 'Unknown'} |",
        f"| **Last Seen**      | {analysis.get('last_seen') or 'Unknown'} |",
        f"| **Source(s)**      | {', '.join(analysis.get('sources', ['N/A']))} |",
        "",
    ]

    if analysis.get("tags"):
        lines += [f"**Tags:** {', '.join(analysis['tags'])}", ""]

    lines += [
        "## Recommended Actions",
        "",
        "- [ ] Block / quarantine this indicator at perimeter controls.",
        "- [ ] Search endpoint telemetry and SIEM for prior interactions.",
        "- [ ] Escalate to incident response if internal hits are found.",
        "- [ ] Add to threat intelligence platform for tracking.",
        "",
        "---",
        f"*Flash report generated by CTI Tracker | {now}*",
    ]

    return title, "\n".join(lines)
