import Link from "next/link";
import { LegalShell } from "@/components/landing/LegalShell";

function Section({ num, title, children }: { num: string; title: string; children: React.ReactNode }) {
  return (
    <section>
      <div className="flex items-baseline gap-3 mb-3">
        <span className="text-[11px] font-mono text-blue-400 shrink-0">{num}</span>
        <h2 className="text-sm font-bold text-zinc-200 uppercase tracking-wide">{title}</h2>
      </div>
      <div className="pl-8 text-sm text-zinc-400 leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

export default function DisclaimerPage() {
  return (
    <LegalShell
      title="Intelligence Disclaimer"
      subtitle="Important limitations and attributions governing the use of threat intelligence data and generated reports on this platform."
      updated="June 2026"
    >
      <Section num="01" title="Informational Purpose Only">
        <p>
          All data, indicators of compromise (IOCs), MITRE ATT&amp;CK mappings, and intelligence reports
          provided by CTI Tracker are for{" "}
          <strong className="text-zinc-300">informational and educational purposes only</strong>. This
          platform is an independent portfolio project and is not a commercial threat intelligence
          product. It should not be used as the authoritative or sole basis for any security decision.
        </p>
      </Section>

      <Section num="02" title="Data Accuracy & False Positives">
        <p>
          IOC data is sourced from publicly available threat intelligence feeds. These feeds may contain{" "}
          <strong className="text-zinc-300">false positives</strong> — indicators incorrectly attributed
          to malicious activity. Acting on unvalidated indicators (e.g., blocking an IP address or
          domain in production) can disrupt legitimate services.
        </p>
        <p>
          Always validate indicators through additional sources and context before taking any operational
          action. CTI Tracker does not guarantee the accuracy, completeness, or currency of any
          indicator or intelligence output.
        </p>
      </Section>

      <Section num="03" title="Third-Party Data Attribution">
        <p>IOC data displayed on this platform is sourced from the following providers:</p>
        <ul className="mt-2 space-y-4 list-none">
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">·</span>
            <div>
              <strong className="text-zinc-300">MalwareBazaar, URLhaus, FeodoTracker</strong>
              <br />
              Provided by <strong className="text-zinc-300">abuse.ch</strong> under the{" "}
              <a
                href="https://creativecommons.org/publicdomain/zero/1.0/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-zinc-400 hover:text-zinc-200 underline transition-colors"
              >
                CC0 1.0 Universal
              </a>{" "}
              public domain dedication. These datasets are made available by abuse.ch to help the
              community improve internet security.
            </div>
          </li>
          <li className="flex gap-2">
            <span className="text-blue-400 shrink-0">·</span>
            <div>
              <strong className="text-zinc-300">MITRE ATT&amp;CK®</strong>
              <br />
              © 2024 The MITRE Corporation. Used under the{" "}
              <a
                href="https://github.com/mitre-attack/attack-stix-data/blob/master/LICENSE"
                target="_blank"
                rel="noopener noreferrer"
                className="text-zinc-400 hover:text-zinc-200 underline transition-colors"
              >
                Apache 2.0 License
              </a>
              . &quot;ATT&amp;CK&quot; and &quot;MITRE ATT&amp;CK&quot; are registered trademarks of
              The MITRE Corporation. CTI Tracker is not affiliated with or endorsed by MITRE.
            </div>
          </li>
        </ul>
      </Section>

      <Section num="04" title="TLP Classification">
        <p>
          Intelligence reports generated by this platform may be assigned a{" "}
          <strong className="text-zinc-300">Traffic Light Protocol (TLP)</strong> classification per
          the{" "}
          <a
            href="https://www.first.org/tlp/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-zinc-400 hover:text-zinc-200 underline transition-colors"
          >
            FIRST.org TLP standard
          </a>
          . Users are responsible for honoring the distribution restrictions associated with each TLP
          level. CTI Tracker does not technically enforce TLP restrictions — compliance is the
          responsibility of the report author and recipients.
        </p>
        <ul className="mt-3 space-y-1.5 list-none text-xs">
          <li className="flex gap-2.5 items-baseline">
            <span className="font-bold text-white shrink-0 w-14">WHITE</span>
            <span>Unrestricted. May be shared publicly.</span>
          </li>
          <li className="flex gap-2.5 items-baseline">
            <span className="font-bold text-green-400 shrink-0 w-14">GREEN</span>
            <span>May be shared within the community or sector, but not publicly.</span>
          </li>
          <li className="flex gap-2.5 items-baseline">
            <span className="font-bold text-amber-400 shrink-0 w-14">AMBER</span>
            <span>Restricted to the organization and named recipients only.</span>
          </li>
          <li className="flex gap-2.5 items-baseline">
            <span className="font-bold text-red-400 shrink-0 w-14">RED</span>
            <span>For named recipients only. Not for disclosure beyond those present.</span>
          </li>
        </ul>
      </Section>

      <Section num="05" title="No Liability for Actions Taken">
        <p>
          CTI Tracker and its operators accept no liability for any security decision, operational
          action, financial loss, or other consequence arising from use of or reliance on data or
          reports provided by this platform. Users assume all responsibility for how they interpret
          and act upon platform outputs.
        </p>
      </Section>

      <div className="pt-4 border-t border-zinc-800">
        <p className="text-xs text-zinc-600">
          See also:{" "}
          <Link href="/legal/terms" className="text-zinc-500 hover:text-zinc-300 underline transition-colors">
            Terms of Service
          </Link>{" "}
          ·{" "}
          <Link href="/legal/privacy" className="text-zinc-500 hover:text-zinc-300 underline transition-colors">
            Privacy Policy
          </Link>
        </p>
      </div>
    </LegalShell>
  );
}
